version: "3"
services:
    website:
        image: anax/dev
        ports:
            - "8080:80"
        volumes:
            - .:/app
            - ./config/docker/dbwebb.se.conf:/etc/apache2/sites-enabled/000-default.conf
